### ISSUE TITLE
PPResume by LM 

### ISSUE THREAD

**Issue by kausal-flow** [kausalflow/tools#119]
2024-12-25T08:18:41.330Z
35
<strong>LM</strong> A LaTeX Based Resume Builder that helps people create beautifully typed resumes in minutes
PPResume
LMA LaTeX Based Resume Builder that helps people create beautifully typed resumes in minutes

**Comment by emptymalei** [comment]
https://github.com/kausalflow/tools/commit/c24bfc72645ceed5e92d4ce4aae1ce1fcd71780f
