### ISSUE TITLE
Typeform typo

### ISSUE THREAD

**Issue by rosano** [kausalflow/tools#46]
I think seminar was spelled 'senimar' in the category selector.

**Comment by rosano** [comment]
<img width="802" alt="Screen Shot 2022-01-08 at 17 44 49" src="https://user-images.githubusercontent.com/1680612/148662399-3291b2fb-227d-4db2-9e75-1268a9c70945.png">

https://form.typeform.com/to/Gi9Xfc

**Comment by emptymalei** [comment]
Hi @rosano, thanks for the issue. It is now fixed in the form.
